services:
  pgdb:
    build: .
    env_file: 
      - .env
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      pgnet:
        ipv4_address: 10.0.27.242
    restart: unless-stopped

networks:
  pgnet:
    name: pgnet
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.27.0/24
          gateway: 10.0.27.1