-- tables that match stats.nba.com json responses
create table intake.gm_player (
    season_id int not null,
    player_id bigint not null,
    player_name varchar(255),
    team_id bigint not null,
    team_abbreviation varchar(3),
    team_name varchar(255),
    game_id bigint not null,
    game_date date,
    matchup varchar(50),
    wl varchar(1),
    min int,
    fgm int,
    fga int,
    fg_pct numeric(5, 4),
    fg3m int,
    fg3a int,
    fg3_pct numeric(5, 4),
    ftm int,
    fta int,
    ft_pct numeric(5, 4),
    oreb int,
    dreb int,
    reb int,
    ast int,
    stl int,
    blk int,
    tov int,
    pf int,
    pts int,
    plus_minus int,
    fantasy_pts numeric(3, 1),
    video_available smallint,
    primary key (game_id, player_id)
);

create table intake.gm_team (
    season_id int not null,
    team_id bigint not null,
    team_abbreviation varchar(3),
    team_name varchar(255),
    game_id bigint not null,
    game_date date,
    matchup varchar(50),
    wl varchar(1),
    min int,
    fgm int,
    fga int,
    fg_pct numeric(5, 4),
    fg3m int,
    fg3a int,
    fg3_pct numeric(5, 4),
    ftm int,
    fta int,
    ft_pct numeric(5, 4),
    oreb int,
    dreb int,
    reb int,
    ast int,
    stl int,
    blk int,
    tov int,
    pf int,
    pts int,
    plus_minus int,
    video_available smallint,
    primary key (game_id, team_id)
);