create table stats.pbox (
    lg_id int references lg.league(lg_id),
    team_id bigint not null references lg.team(team_id),
    game_id bigint not null,
    player_id bigint not null references lg.plr(player_id),
    gdate date,
    matchup varchar(50),
    wl varchar(1),
    mins int,
    pts int,
    ast int,
    reb int,
    stl int,
    blk int,
    tov int,
    oreb int,
    dreb int,
    foul int,
    pm int,
    fgm int,
    fga int,
    fgp numeric(5, 4),
    f3m int,
    f3a int,
    f3p numeric(5, 4),
    ftm int,
    fta int,
    ftp numeric(5, 4),
    primary key (game_id, player_id)
);

create table stats.tbox (
    lg_id int references lg.league(lg_id),
    team_id bigint not null references lg.team(team_id),
    game_id bigint not null,
    gdate date,
    matchup varchar(50),
    wl varchar(1),
    mins int,
    pts int,
    ast int,
    reb int,
    stl int,
    blk int,
    tov int,
    oreb int,
    dreb int,
    foul int,
    pm int,
    fgm int,
    fga int,
    fgp numeric(5, 4),
    f3m int,
    f3a int,
    f3p numeric(5, 4),
    ftm int,
    fta int,
    ftp numeric(5, 4),
    primary key (game_id, team_id)
);