create table stats.pbox (
    game_id bigint not null,
    team_id bigint not null references league.team(team_id),
    lg_id int references league.lg(lg_id),
    player_id bigint not null references player.all(player_id),
    player varchar(255),
    matchup varchar(50),
    wl varchar(1),
    mins int,
    pts int,
    ast int,
    reb int,
    stl int,
    blk int,
    tov int,
    oreb int,
    dreb int,
    foul int,
    pm int,
    fgm int,
    fga int,
    fgp numeric(5, 4),
    f3m int,
    f3a int,
    f3p numeric(5, 4),
    ftm int,
    fta int,
    ftp numeric(5, 4),
    primary key (game_id, player_id)
);

create table stats.tbox (
    game_id bigint not null,
    team_id bigint not null references league.team(team_id),
    lg_id int references league.lg(lg_id),
    matchup varchar(50),
    wl varchar(1),
    mins int,
    pts int,
    ast int,
    reb int,
    stl int,
    blk int,
    tov int,
    oreb int,
    dreb int,
    foul int,
    pm int,
    fgm int,
    fga int,
    fgp numeric(5, 4),
    f3m int,
    f3a int,
    f3p numeric(5, 4),
    ftm int,
    fta int,
    ftp numeric(5, 4),
    primary key (game_id, team_id)
);